print(f"B: ord('B')")
print(f"C: ord('C')")
print(f"D: ord('D')")
print(f"b: ord('b')")
print(f"c: ord('c')")
print(f"d: ord('d')")
print(f"0: ord('0')")
print(f"1: ord('1')")
print(f"2: ord('2')")
print(f"$: ord('$')")
print(f"*: ord('*')")
print(f"+: ord('+')")
print(f"Space: ord(' ')")
